import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Auto-generated sidebar for projects - each project folder will have its own sidebar
  projectsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'projects',
    },
  ],
  generalSidebar: [
    {
      type: 'autogenerated',
      dirName: 'general',
    },
  ],
  incidentsSidebar: [
    {
      type: 'autogenerated',
      dirName: 'incidents',
    },
  ],
};

export default sidebars;
